name: Generate ASCII Artwork

on:
  push:
  workflow_dispatch:    # optional: lets you run this manually from Actions UI

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install -y cowsay

      - name: Execute cowsay command and save output
        run: cowsay -f dragon 'Run for cover, I am a DRAGON....RAWR' >> dragon.txt

      - name: Test file contains "dragon"
        run: grep -i "dragon" dragon.txt

      - name: Read file
        run: cat dragon.txt

      - name: List repo files
        run: ls -ltra