name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest   # Correct indentation + space after colon

    steps:
      - name: Welcome message
        run: echo "My first job in GitHub Actions"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md

