name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest   # Correct indentation + space after colon

    steps:
      - name: checkout repo
        uses: actions/checkout@v5
       
      - name: List and readfile
        run: | 
             echo "My first job in GitHub Actions"
             ls -ltra
             cat README.md
   
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I am a Dragon... RAWR" >> dragon.txt