name: Generate ASCII Artwork

on:
  push:
  workflow_dispatch:    # optional: lets you run this manually from Actions UI

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -ltr
      
      - name: executing shell script
        run: ./ascii-scripts.sh
       
